
// This file has been generated by the GUI designer. Do not modify.

public partial class FormLog
{
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.HBox hbox5;
	
	private global::Gtk.Button buttonClear;
	
	private global::Gtk.Button buttonExport;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.TextView richTextBox1;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget FormLog
		this.Name = "FormLog";
		this.Title = global::Mono.Unix.Catalog.GetString ("FormLog");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(6));
		this.Gravity = ((global::Gdk.Gravity)(5));
		// Container child FormLog.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.buttonClear = new global::Gtk.Button ();
		this.buttonClear.CanFocus = true;
		this.buttonClear.Name = "buttonClear";
		this.buttonClear.UseUnderline = true;
		this.buttonClear.Label = global::Mono.Unix.Catalog.GetString ("清空");
		this.hbox5.Add (this.buttonClear);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.buttonClear]));
		w1.Position = 0;
		// Container child hbox5.Gtk.Box+BoxChild
		this.buttonExport = new global::Gtk.Button ();
		this.buttonExport.CanFocus = true;
		this.buttonExport.Name = "buttonExport";
		this.buttonExport.UseUnderline = true;
		this.buttonExport.Label = global::Mono.Unix.Catalog.GetString ("导出");
		this.hbox5.Add (this.buttonExport);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.buttonExport]));
		w2.Position = 1;
		this.vbox1.Add (this.hbox5);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox5]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.richTextBox1 = new global::Gtk.TextView ();
		this.richTextBox1.CanFocus = true;
		this.richTextBox1.Name = "richTextBox1";
		this.GtkScrolledWindow.Add (this.richTextBox1);
		this.vbox1.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
		w5.Position = 1;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.buttonClear.Clicked += new global::System.EventHandler (this.buttonClear_Click);
		this.buttonExport.Clicked += new global::System.EventHandler (this.buttonExport_Click);
	}
}
