
// This file has been generated by the GUI designer. Do not modify.

public partial class FormMain
{
	private global::Gtk.VBox vbox3;
	
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.ComboBox programBox;
	
	private global::Gtk.Button buttonCode;
	
	private global::Gtk.Button buttonData;
	
	private global::Gtk.CheckButton checkCreate;
	
	private global::Gtk.CheckButton checkCompress;
	
	private global::Gtk.Button buttonLog;
	
	private global::Gtk.HBox hbox2;
	
	private global::Gtk.Button buttonSpwan;
	
	private global::Gtk.Label label1;
	
	private global::Gtk.Entry packageText;
	
	private global::Gtk.Button buttonLanguage;
	
	private global::Gtk.Button buttonRefreshLanguage;
	
	private global::Gtk.HBox hbox3;
	
	private global::Gtk.CheckButton getManager;
	
	private global::Gtk.CheckButton Language;
	
	private global::Gtk.CheckButton refreshNote;
	
	private global::Gtk.Button clearPath;
	
	private global::Gtk.HBox hbox4;
	
	private global::Gtk.Label label2;
	
	private global::Gtk.Entry textTableConfig;
	
	private global::Gtk.Button button4;
	
	private global::Gtk.HBox hbox5;
	
	private global::Gtk.Label label3;
	
	private global::Gtk.Entry textTableFolder;
	
	private global::Gtk.Button buttonTransformFolder;
	
	private global::Gtk.HBox hbox6;
	
	private global::Gtk.Label label4;
	
	private global::Gtk.Entry textTransformFiles;
	
	private global::Gtk.Button selectTransformFiles;
	
	private global::Gtk.Button buttonTransform;
	
	private global::Gtk.HBox hbox7;
	
	private global::Gtk.Label label5;
	
	private global::Gtk.Entry textRollbackFiles;
	
	private global::Gtk.Button selectRollbackFiles;
	
	private global::Gtk.Button buttonRollback;
	
	private global::Gtk.HBox hbox8;
	
	private global::Gtk.Label label6;
	
	private global::Gtk.Entry textMessage;
	
	private global::Gtk.Button buttonMessage;
	
	private global::Gtk.HBox hbox9;
	
	private global::Gtk.Label label7;
	
	private global::Gtk.Entry textDatabase;
	
	private global::Gtk.Button buttonDatabase;
	
	private global::Gtk.ProgressBar progressBar;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget FormMain
		this.Name = "FormMain";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child FormMain.Gtk.Container+ContainerChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Homogeneous = true;
		this.vbox3.BorderWidth = ((uint)(3));
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.programBox = global::Gtk.ComboBox.NewText ();
		this.programBox.Name = "programBox";
		this.hbox1.Add (this.programBox);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.programBox]));
		w1.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.buttonCode = new global::Gtk.Button ();
		this.buttonCode.CanFocus = true;
		this.buttonCode.Name = "buttonCode";
		this.buttonCode.UseUnderline = true;
		this.buttonCode.Label = global::Mono.Unix.Catalog.GetString ("代码路径");
		this.hbox1.Add (this.buttonCode);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonCode]));
		w2.Position = 1;
		// Container child hbox1.Gtk.Box+BoxChild
		this.buttonData = new global::Gtk.Button ();
		this.buttonData.CanFocus = true;
		this.buttonData.Name = "buttonData";
		this.buttonData.UseUnderline = true;
		this.buttonData.Label = global::Mono.Unix.Catalog.GetString ("Data路径");
		this.hbox1.Add (this.buttonData);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonData]));
		w3.Position = 2;
		// Container child hbox1.Gtk.Box+BoxChild
		this.checkCreate = new global::Gtk.CheckButton ();
		this.checkCreate.CanFocus = true;
		this.checkCreate.Name = "checkCreate";
		this.checkCreate.Label = global::Mono.Unix.Catalog.GetString ("默认生成");
		this.checkCreate.DrawIndicator = true;
		this.checkCreate.UseUnderline = true;
		this.hbox1.Add (this.checkCreate);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.checkCreate]));
		w4.Position = 3;
		w4.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.checkCompress = new global::Gtk.CheckButton ();
		this.checkCompress.CanFocus = true;
		this.checkCompress.Name = "checkCompress";
		this.checkCompress.Label = global::Mono.Unix.Catalog.GetString ("gzip压缩");
		this.checkCompress.DrawIndicator = true;
		this.checkCompress.UseUnderline = true;
		this.hbox1.Add (this.checkCompress);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.checkCompress]));
		w5.Position = 4;
		w5.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.buttonLog = new global::Gtk.Button ();
		this.buttonLog.CanFocus = true;
		this.buttonLog.Name = "buttonLog";
		this.buttonLog.UseUnderline = true;
		this.buttonLog.Label = global::Mono.Unix.Catalog.GetString ("打开日志");
		this.hbox1.Add (this.buttonLog);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonLog]));
		w6.Position = 5;
		this.vbox3.Add (this.hbox1);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox1]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.buttonSpwan = new global::Gtk.Button ();
		this.buttonSpwan.CanFocus = true;
		this.buttonSpwan.Name = "buttonSpwan";
		this.buttonSpwan.UseUnderline = true;
		this.buttonSpwan.Label = global::Mono.Unix.Catalog.GetString ("批量关键字");
		this.hbox2.Add (this.buttonSpwan);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.buttonSpwan]));
		w8.Position = 0;
		// Container child hbox2.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("PackageName");
		this.hbox2.Add (this.label1);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label1]));
		w9.Position = 1;
		w9.Expand = false;
		w9.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.packageText = new global::Gtk.Entry ();
		this.packageText.CanFocus = true;
		this.packageText.Name = "packageText";
		this.packageText.Text = global::Mono.Unix.Catalog.GetString ("PackageName");
		this.packageText.IsEditable = true;
		this.packageText.InvisibleChar = '●';
		this.hbox2.Add (this.packageText);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.packageText]));
		w10.Position = 2;
		// Container child hbox2.Gtk.Box+BoxChild
		this.buttonLanguage = new global::Gtk.Button ();
		this.buttonLanguage.CanFocus = true;
		this.buttonLanguage.Name = "buttonLanguage";
		this.buttonLanguage.UseUnderline = true;
		this.buttonLanguage.Label = global::Mono.Unix.Catalog.GetString ("多国语言");
		this.hbox2.Add (this.buttonLanguage);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.buttonLanguage]));
		w11.Position = 3;
		// Container child hbox2.Gtk.Box+BoxChild
		this.buttonRefreshLanguage = new global::Gtk.Button ();
		this.buttonRefreshLanguage.CanFocus = true;
		this.buttonRefreshLanguage.Name = "buttonRefreshLanguage";
		this.buttonRefreshLanguage.UseUnderline = true;
		this.buttonRefreshLanguage.Label = global::Mono.Unix.Catalog.GetString ("刷新表");
		this.hbox2.Add (this.buttonRefreshLanguage);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.buttonRefreshLanguage]));
		w12.Position = 4;
		this.vbox3.Add (this.hbox2);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox2]));
		w13.Position = 1;
		w13.Expand = false;
		w13.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.getManager = new global::Gtk.CheckButton ();
		this.getManager.CanFocus = true;
		this.getManager.Name = "getManager";
		this.getManager.Label = global::Mono.Unix.Catalog.GetString ("生成Manager");
		this.getManager.DrawIndicator = true;
		this.getManager.UseUnderline = true;
		this.hbox3.Add (this.getManager);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.getManager]));
		w14.Position = 0;
		// Container child hbox3.Gtk.Box+BoxChild
		this.Language = new global::Gtk.CheckButton ();
		this.Language.CanFocus = true;
		this.Language.Name = "Language";
		this.Language.Label = global::Mono.Unix.Catalog.GetString ("生成多国语言");
		this.Language.DrawIndicator = true;
		this.Language.UseUnderline = true;
		this.hbox3.Add (this.Language);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.Language]));
		w15.Position = 1;
		// Container child hbox3.Gtk.Box+BoxChild
		this.refreshNote = new global::Gtk.CheckButton ();
		this.refreshNote.CanFocus = true;
		this.refreshNote.Name = "refreshNote";
		this.refreshNote.Label = global::Mono.Unix.Catalog.GetString ("刷新表注释(必须关闭Excel)");
		this.refreshNote.DrawIndicator = true;
		this.refreshNote.UseUnderline = true;
		this.hbox3.Add (this.refreshNote);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.refreshNote]));
		w16.Position = 2;
		// Container child hbox3.Gtk.Box+BoxChild
		this.clearPath = new global::Gtk.Button ();
		this.clearPath.CanFocus = true;
		this.clearPath.Name = "clearPath";
		this.clearPath.UseUnderline = true;
		this.clearPath.Label = global::Mono.Unix.Catalog.GetString ("清楚目录");
		this.hbox3.Add (this.clearPath);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.clearPath]));
		w17.Position = 3;
		this.vbox3.Add (this.hbox3);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox3]));
		w18.Position = 2;
		w18.Expand = false;
		w18.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("选择配置路径");
		this.hbox4.Add (this.label2);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label2]));
		w19.Position = 0;
		w19.Expand = false;
		w19.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.textTableConfig = new global::Gtk.Entry ();
		this.textTableConfig.CanFocus = true;
		this.textTableConfig.Name = "textTableConfig";
		this.textTableConfig.IsEditable = true;
		this.textTableConfig.InvisibleChar = '●';
		this.hbox4.Add (this.textTableConfig);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.textTableConfig]));
		w20.Position = 1;
		// Container child hbox4.Gtk.Box+BoxChild
		this.button4 = new global::Gtk.Button ();
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		this.button4.Label = global::Mono.Unix.Catalog.GetString ("TinyPNG");
		this.hbox4.Add (this.button4);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.button4]));
		w21.Position = 2;
		this.vbox3.Add (this.hbox4);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox4]));
		w22.Position = 3;
		w22.Expand = false;
		w22.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("选择要转换的文件夹");
		this.hbox5.Add (this.label3);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label3]));
		w23.Position = 0;
		w23.Expand = false;
		w23.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.textTableFolder = new global::Gtk.Entry ();
		this.textTableFolder.CanFocus = true;
		this.textTableFolder.Name = "textTableFolder";
		this.textTableFolder.IsEditable = true;
		this.textTableFolder.InvisibleChar = '●';
		this.hbox5.Add (this.textTableFolder);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.textTableFolder]));
		w24.Position = 1;
		// Container child hbox5.Gtk.Box+BoxChild
		this.buttonTransformFolder = new global::Gtk.Button ();
		this.buttonTransformFolder.CanFocus = true;
		this.buttonTransformFolder.Name = "buttonTransformFolder";
		this.buttonTransformFolder.UseUnderline = true;
		this.buttonTransformFolder.Label = global::Mono.Unix.Catalog.GetString ("转换");
		this.hbox5.Add (this.buttonTransformFolder);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.buttonTransformFolder]));
		w25.Position = 2;
		this.vbox3.Add (this.hbox5);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox5]));
		w26.Position = 4;
		w26.Expand = false;
		w26.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox ();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("选择要转换的文件");
		this.hbox6.Add (this.label4);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label4]));
		w27.Position = 0;
		w27.Expand = false;
		w27.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.textTransformFiles = new global::Gtk.Entry ();
		this.textTransformFiles.CanFocus = true;
		this.textTransformFiles.Name = "textTransformFiles";
		this.textTransformFiles.IsEditable = true;
		this.textTransformFiles.InvisibleChar = '●';
		this.hbox6.Add (this.textTransformFiles);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.textTransformFiles]));
		w28.Position = 1;
		// Container child hbox6.Gtk.Box+BoxChild
		this.selectTransformFiles = new global::Gtk.Button ();
		this.selectTransformFiles.CanFocus = true;
		this.selectTransformFiles.Name = "selectTransformFiles";
		this.selectTransformFiles.UseUnderline = true;
		this.selectTransformFiles.Label = global::Mono.Unix.Catalog.GetString ("选择");
		this.hbox6.Add (this.selectTransformFiles);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.selectTransformFiles]));
		w29.Position = 2;
		// Container child hbox6.Gtk.Box+BoxChild
		this.buttonTransform = new global::Gtk.Button ();
		this.buttonTransform.CanFocus = true;
		this.buttonTransform.Name = "buttonTransform";
		this.buttonTransform.UseUnderline = true;
		this.buttonTransform.Label = global::Mono.Unix.Catalog.GetString ("转换");
		this.hbox6.Add (this.buttonTransform);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.buttonTransform]));
		w30.Position = 3;
		this.vbox3.Add (this.hbox6);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox6]));
		w31.Position = 5;
		w31.Expand = false;
		w31.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox ();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("选择要反转的文件");
		this.hbox7.Add (this.label5);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.label5]));
		w32.Position = 0;
		w32.Expand = false;
		w32.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.textRollbackFiles = new global::Gtk.Entry ();
		this.textRollbackFiles.CanFocus = true;
		this.textRollbackFiles.Name = "textRollbackFiles";
		this.textRollbackFiles.IsEditable = true;
		this.textRollbackFiles.InvisibleChar = '●';
		this.hbox7.Add (this.textRollbackFiles);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.textRollbackFiles]));
		w33.Position = 1;
		// Container child hbox7.Gtk.Box+BoxChild
		this.selectRollbackFiles = new global::Gtk.Button ();
		this.selectRollbackFiles.CanFocus = true;
		this.selectRollbackFiles.Name = "selectRollbackFiles";
		this.selectRollbackFiles.UseUnderline = true;
		this.selectRollbackFiles.Label = global::Mono.Unix.Catalog.GetString ("选择");
		this.hbox7.Add (this.selectRollbackFiles);
		global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.selectRollbackFiles]));
		w34.Position = 2;
		// Container child hbox7.Gtk.Box+BoxChild
		this.buttonRollback = new global::Gtk.Button ();
		this.buttonRollback.CanFocus = true;
		this.buttonRollback.Name = "buttonRollback";
		this.buttonRollback.UseUnderline = true;
		this.buttonRollback.Label = global::Mono.Unix.Catalog.GetString ("转换");
		this.hbox7.Add (this.buttonRollback);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.buttonRollback]));
		w35.Position = 3;
		this.vbox3.Add (this.hbox7);
		global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox7]));
		w36.Position = 6;
		w36.Expand = false;
		w36.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox8 = new global::Gtk.HBox ();
		this.hbox8.Name = "hbox8";
		this.hbox8.Spacing = 6;
		// Container child hbox8.Gtk.Box+BoxChild
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("选择协议路径");
		this.hbox8.Add (this.label6);
		global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.label6]));
		w37.Position = 0;
		w37.Expand = false;
		w37.Fill = false;
		// Container child hbox8.Gtk.Box+BoxChild
		this.textMessage = new global::Gtk.Entry ();
		this.textMessage.CanFocus = true;
		this.textMessage.Name = "textMessage";
		this.textMessage.IsEditable = true;
		this.textMessage.InvisibleChar = '●';
		this.hbox8.Add (this.textMessage);
		global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.textMessage]));
		w38.Position = 1;
		// Container child hbox8.Gtk.Box+BoxChild
		this.buttonMessage = new global::Gtk.Button ();
		this.buttonMessage.CanFocus = true;
		this.buttonMessage.Name = "buttonMessage";
		this.buttonMessage.UseUnderline = true;
		this.buttonMessage.Label = global::Mono.Unix.Catalog.GetString ("转换");
		this.hbox8.Add (this.buttonMessage);
		global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.buttonMessage]));
		w39.Position = 2;
		this.vbox3.Add (this.hbox8);
		global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox8]));
		w40.Position = 7;
		w40.Expand = false;
		w40.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox9 = new global::Gtk.HBox ();
		this.hbox9.Name = "hbox9";
		this.hbox9.Spacing = 6;
		// Container child hbox9.Gtk.Box+BoxChild
		this.label7 = new global::Gtk.Label ();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("选择数据库配置路径");
		this.hbox9.Add (this.label7);
		global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.label7]));
		w41.Position = 0;
		w41.Expand = false;
		w41.Fill = false;
		// Container child hbox9.Gtk.Box+BoxChild
		this.textDatabase = new global::Gtk.Entry ();
		this.textDatabase.CanFocus = true;
		this.textDatabase.Name = "textDatabase";
		this.textDatabase.IsEditable = true;
		this.textDatabase.InvisibleChar = '●';
		this.hbox9.Add (this.textDatabase);
		global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.textDatabase]));
		w42.Position = 1;
		// Container child hbox9.Gtk.Box+BoxChild
		this.buttonDatabase = new global::Gtk.Button ();
		this.buttonDatabase.CanFocus = true;
		this.buttonDatabase.Name = "buttonDatabase";
		this.buttonDatabase.UseUnderline = true;
		this.buttonDatabase.Label = global::Mono.Unix.Catalog.GetString ("转换");
		this.hbox9.Add (this.buttonDatabase);
		global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.buttonDatabase]));
		w43.Position = 2;
		this.vbox3.Add (this.hbox9);
		global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox9]));
		w44.Position = 8;
		w44.Expand = false;
		w44.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.progressBar = new global::Gtk.ProgressBar ();
		this.progressBar.Name = "progressBar";
		this.progressBar.Text = global::Mono.Unix.Catalog.GetString ("11111");
		this.progressBar.Fraction = 0.5D;
		this.vbox3.Add (this.progressBar);
		global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.progressBar]));
		w45.Position = 9;
		w45.Expand = false;
		w45.Fill = false;
		this.Add (this.vbox3);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 664;
		this.DefaultHeight = 355;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.programBox.Changed += new global::System.EventHandler (this.programBox_SelectedIndexChanged);
		this.buttonCode.Clicked += new global::System.EventHandler (this.buttonCode_Click);
		this.buttonData.Clicked += new global::System.EventHandler (this.buttonData_Click);
		this.buttonLog.Clicked += new global::System.EventHandler (this.buttonLog_Click);
		this.buttonSpwan.Clicked += new global::System.EventHandler (this.buttonSpwan_Click);
		this.buttonTransformFolder.Clicked += new global::System.EventHandler (this.buttonTransformFolder_Click);
		this.selectTransformFiles.Clicked += new global::System.EventHandler (this.selectTransformFiles_Click);
		this.buttonTransform.Clicked += new global::System.EventHandler (this.buttonTransform_Click);
		this.selectRollbackFiles.Clicked += new global::System.EventHandler (this.selectRollbackFiles_Click);
		this.buttonRollback.Clicked += new global::System.EventHandler (this.buttonRollback_Click);
		this.buttonMessage.Clicked += new global::System.EventHandler (this.buttonMessage_Click);
		this.buttonDatabase.Clicked += new global::System.EventHandler (this.buttonDatabase_Click);
	}
}
