
// This file has been generated by the GUI designer. Do not modify.

public partial class FormPath
{
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.Button button1;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.TextView richTextBox1;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget FormPath
		this.Name = "FormPath";
		this.Title = global::Mono.Unix.Catalog.GetString ("FormPath");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child FormPath.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.button1 = new global::Gtk.Button ();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString ("打开路径");
		this.vbox1.Add (this.button1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.button1]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.richTextBox1 = new global::Gtk.TextView ();
		this.richTextBox1.CanFocus = true;
		this.richTextBox1.Name = "richTextBox1";
		this.GtkScrolledWindow.Add (this.richTextBox1);
		this.vbox1.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
		w3.Position = 1;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.button1.Clicked += new global::System.EventHandler (this.button1_Click);
	}
}
