
// This file has been generated by the GUI designer. Do not modify.

public partial class LanguageWidget
{
	private global::Gtk.Expander LanguageExpander;
	
	private global::Gtk.VBox vbox5;
	
	private global::Gtk.Frame frame3;
	
	private global::Gtk.Alignment GtkAlignment2;
	
	private global::Gtk.VBox vbox13;
	
	private global::Gtk.Frame CodeFrame;
	
	private global::Gtk.Alignment GtkAlignment;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.TextView CodePath;
	
	private global::Gtk.Label GtkLabel1;
	
	private global::Gtk.Frame DataFrame;
	
	private global::Gtk.Alignment GtkAlignment1;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow1;
	
	private global::Gtk.TextView DataPath;
	
	private global::Gtk.Label GtkLabel3;
	
	private global::Gtk.HBox hbox3;
	
	private global::Gtk.CheckButton CheckCreate;
	
	private global::Gtk.CheckButton CheckCompress;
	
	private global::Gtk.Label GtkLabel4;
	
	private global::Gtk.Label LanguageName;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget LanguageWidget
		global::Stetic.BinContainer.Attach (this);
		this.Name = "LanguageWidget";
		// Container child LanguageWidget.Gtk.Container+ContainerChild
		this.LanguageExpander = new global::Gtk.Expander (null);
		this.LanguageExpander.CanFocus = true;
		this.LanguageExpander.Name = "LanguageExpander";
		this.LanguageExpander.Expanded = true;
		// Container child LanguageExpander.Gtk.Container+ContainerChild
		this.vbox5 = new global::Gtk.VBox ();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.frame3 = new global::Gtk.Frame ();
		this.frame3.Name = "frame3";
		this.frame3.ShadowType = ((global::Gtk.ShadowType)(4));
		this.frame3.BorderWidth = ((uint)(2));
		// Container child frame3.Gtk.Container+ContainerChild
		this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment2.Name = "GtkAlignment2";
		this.GtkAlignment2.LeftPadding = ((uint)(12));
		// Container child GtkAlignment2.Gtk.Container+ContainerChild
		this.vbox13 = new global::Gtk.VBox ();
		this.vbox13.Name = "vbox13";
		this.vbox13.Spacing = 6;
		// Container child vbox13.Gtk.Box+BoxChild
		this.CodeFrame = new global::Gtk.Frame ();
		this.CodeFrame.Name = "CodeFrame";
		this.CodeFrame.ShadowType = ((global::Gtk.ShadowType)(0));
		this.CodeFrame.LabelXalign = 0.1F;
		// Container child CodeFrame.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.CodePath = new global::Gtk.TextView ();
		this.CodePath.TooltipMarkup = "代码路径,每一行代表一个路径";
		this.CodePath.HeightRequest = 100;
		this.CodePath.CanFocus = true;
		this.CodePath.ExtensionEvents = ((global::Gdk.ExtensionMode)(1));
		this.CodePath.Name = "CodePath";
		this.GtkScrolledWindow.Add (this.CodePath);
		this.GtkAlignment.Add (this.GtkScrolledWindow);
		this.CodeFrame.Add (this.GtkAlignment);
		this.GtkLabel1 = new global::Gtk.Label ();
		this.GtkLabel1.Name = "GtkLabel1";
		this.GtkLabel1.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>代码路径</b>");
		this.GtkLabel1.UseMarkup = true;
		this.CodeFrame.LabelWidget = this.GtkLabel1;
		this.vbox13.Add (this.CodeFrame);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.CodeFrame]));
		w4.Position = 0;
		// Container child vbox13.Gtk.Box+BoxChild
		this.DataFrame = new global::Gtk.Frame ();
		this.DataFrame.Name = "DataFrame";
		this.DataFrame.ShadowType = ((global::Gtk.ShadowType)(0));
		this.DataFrame.LabelXalign = 0.1F;
		// Container child DataFrame.Gtk.Container+ContainerChild
		this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment1.Name = "GtkAlignment1";
		this.GtkAlignment1.LeftPadding = ((uint)(12));
		// Container child GtkAlignment1.Gtk.Container+ContainerChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.DataPath = new global::Gtk.TextView ();
		this.DataPath.TooltipMarkup = "Data路径,每一行代表一个路径";
		this.DataPath.HeightRequest = 100;
		this.DataPath.CanFocus = true;
		this.DataPath.Name = "DataPath";
		this.GtkScrolledWindow1.Add (this.DataPath);
		this.GtkAlignment1.Add (this.GtkScrolledWindow1);
		this.DataFrame.Add (this.GtkAlignment1);
		this.GtkLabel3 = new global::Gtk.Label ();
		this.GtkLabel3.Name = "GtkLabel3";
		this.GtkLabel3.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Data路径</b>");
		this.GtkLabel3.UseMarkup = true;
		this.DataFrame.LabelWidget = this.GtkLabel3;
		this.vbox13.Add (this.DataFrame);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.DataFrame]));
		w8.Position = 1;
		// Container child vbox13.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.CheckCreate = new global::Gtk.CheckButton ();
		this.CheckCreate.TooltipMarkup = "默认是否生成此语言";
		this.CheckCreate.CanFocus = true;
		this.CheckCreate.Name = "CheckCreate";
		this.CheckCreate.Label = global::Mono.Unix.Catalog.GetString ("默认是否生成");
		this.CheckCreate.DrawIndicator = true;
		this.CheckCreate.UseUnderline = true;
		this.CheckCreate.Xalign = 0.2F;
		this.hbox3.Add (this.CheckCreate);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.CheckCreate]));
		w9.Position = 0;
		// Container child hbox3.Gtk.Box+BoxChild
		this.CheckCompress = new global::Gtk.CheckButton ();
		this.CheckCompress.TooltipMarkup = "生成的Data文件是否使用gzip压缩";
		this.CheckCompress.CanFocus = true;
		this.CheckCompress.Name = "CheckCompress";
		this.CheckCompress.Label = global::Mono.Unix.Catalog.GetString ("是否使用gzip压缩");
		this.CheckCompress.DrawIndicator = true;
		this.CheckCompress.UseUnderline = true;
		this.CheckCompress.Relief = ((global::Gtk.ReliefStyle)(1));
		this.hbox3.Add (this.CheckCompress);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.CheckCompress]));
		w10.Position = 1;
		this.vbox13.Add (this.hbox3);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.hbox3]));
		w11.Position = 2;
		w11.Expand = false;
		w11.Fill = false;
		this.GtkAlignment2.Add (this.vbox13);
		this.frame3.Add (this.GtkAlignment2);
		this.GtkLabel4 = new global::Gtk.Label ();
		this.GtkLabel4.Name = "GtkLabel4";
		this.GtkLabel4.UseMarkup = true;
		this.frame3.LabelWidget = this.GtkLabel4;
		this.vbox5.Add (this.frame3);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.frame3]));
		w14.Position = 0;
		this.LanguageExpander.Add (this.vbox5);
		this.LanguageName = new global::Gtk.Label ();
		this.LanguageName.Name = "LanguageName";
		this.LanguageName.LabelProp = global::Mono.Unix.Catalog.GetString ("语言名称");
		this.LanguageName.UseMarkup = true;
		this.LanguageName.UseUnderline = true;
		this.LanguageName.Justify = ((global::Gtk.Justification)(2));
		this.LanguageName.MaxWidthChars = 532;
		this.LanguageName.SingleLineMode = true;
		this.LanguageExpander.LabelWidget = this.LanguageName;
		this.Add (this.LanguageExpander);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.Hide ();
	}
}
