
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action ToolsAction;
	
	private global::Gtk.Action applyAction;
	
	private global::Gtk.Action TinyPNGAction;
	
	private global::Gtk.VBox MenuVBox;
	
	private global::Gtk.MenuBar menubar2;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.HBox MainHBox;
	
	private global::Gtk.ScrolledWindow scrolledwindow1;
	
	private global::Gtk.Alignment alignment3;
	
	private global::Gtk.VBox SettingVBox;
	
	private global::Gtk.ToggleButton ToggleCode;
	
	private global::Gtk.VBox CodeBox;
	
	private global::Gtk.ToggleButton ToggleLanguage;
	
	private global::Gtk.VBox LanguageBox;
	
	private global::Gtk.VBox vbox4;
	
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.Label label8;
	
	private global::Gtk.Entry TextBoxAllLanguages;
	
	private global::Gtk.HBox hbox10;
	
	private global::Gtk.Label label9;
	
	private global::Gtk.Entry TextBoxTranslation;
	
	private global::Gtk.HBox hbox11;
	
	private global::Gtk.Label label10;
	
	private global::Gtk.Entry TextBoxLanguage;
	
	private global::Gtk.ToggleButton ToggleSpawn;
	
	private global::Gtk.VBox SpawnBox;
	
	private global::Gtk.VBox vbox6;
	
	private global::Gtk.HBox hbox12;
	
	private global::Gtk.Label label11;
	
	private global::Gtk.Entry textSpawns;
	
	private global::Gtk.HBox hbox13;
	
	private global::Gtk.Label label12;
	
	private global::Gtk.Entry textDatabase;
	
	private global::Gtk.VBox vbox14;
	
	private global::Gtk.HBox hbox2;
	
	private global::Gtk.Label label1;
	
	private global::Gtk.Entry packageText;
	
	private global::Gtk.Button buttonRefreshLanguage;
	
	private global::Gtk.HBox hbox3;
	
	private global::Gtk.CheckButton getManager;
	
	private global::Gtk.CheckButton Language;
	
	private global::Gtk.CheckButton refreshNote;
	
	private global::Gtk.HBox hbox4;
	
	private global::Gtk.Label label2;
	
	private global::Gtk.Entry textTableConfig;
	
	private global::Gtk.HBox hbox5;
	
	private global::Gtk.Label label3;
	
	private global::Gtk.Entry textTableFolder;
	
	private global::Gtk.Button buttonTransformFolder;
	
	private global::Gtk.HBox hbox6;
	
	private global::Gtk.Label label4;
	
	private global::Gtk.Entry textTransformFiles;
	
	private global::Gtk.Button selectTransformFiles;
	
	private global::Gtk.Button buttonTransform;
	
	private global::Gtk.HBox hbox7;
	
	private global::Gtk.Label label5;
	
	private global::Gtk.Entry textRollbackFiles;
	
	private global::Gtk.Button selectRollbackFiles;
	
	private global::Gtk.Button buttonRollback;
	
	private global::Gtk.HBox hbox8;
	
	private global::Gtk.Label label6;
	
	private global::Gtk.Entry textMessage;
	
	private global::Gtk.Button buttonMessage;
	
	private global::Gtk.HBox hbox9;
	
	private global::Gtk.Label label7;
	
	private global::Gtk.Entry textDatabaseConfig;
	
	private global::Gtk.Button buttonDatabase;
	
	private global::Gtk.ProgressBar progressBar;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow1;
	
	private global::Gtk.TextView TextViewLog;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.ToolsAction = new global::Gtk.Action ("ToolsAction", global::Mono.Unix.Catalog.GetString ("工具"), null, null);
		this.ToolsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("工具");
		w1.Add (this.ToolsAction, null);
		this.applyAction = new global::Gtk.Action ("applyAction", global::Mono.Unix.Catalog.GetString ("TinyPNG"), null, "gtk-apply");
		this.applyAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("TinyPNG");
		w1.Add (this.applyAction, null);
		this.TinyPNGAction = new global::Gtk.Action ("TinyPNGAction", global::Mono.Unix.Catalog.GetString ("TinyPNG"), null, null);
		this.TinyPNGAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("TinyPNG");
		w1.Add (this.TinyPNGAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("转换工具");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Role = "\n";
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.MenuVBox = new global::Gtk.VBox ();
		this.MenuVBox.Name = "MenuVBox";
		this.MenuVBox.Spacing = 6;
		// Container child MenuVBox.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name=\'menubar2\'><menu name=\'ToolsAction\' action=\'ToolsAction\'><menui" +
		"tem name=\'TinyPNGAction\' action=\'TinyPNGAction\'/></menu></menubar></ui>");
		this.menubar2 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar2")));
		this.menubar2.Name = "menubar2";
		this.MenuVBox.Add (this.menubar2);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.MenuVBox [this.menubar2]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child MenuVBox.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		global::Gtk.Viewport w3 = new global::Gtk.Viewport ();
		w3.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child GtkViewport.Gtk.Container+ContainerChild
		this.MainHBox = new global::Gtk.HBox ();
		this.MainHBox.CanFocus = true;
		this.MainHBox.Name = "MainHBox";
		this.MainHBox.Spacing = 10;
		// Container child MainHBox.Gtk.Box+BoxChild
		this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
		this.scrolledwindow1.CanFocus = true;
		this.scrolledwindow1.Name = "scrolledwindow1";
		this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child scrolledwindow1.Gtk.Container+ContainerChild
		global::Gtk.Viewport w4 = new global::Gtk.Viewport ();
		w4.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child GtkViewport1.Gtk.Container+ContainerChild
		this.alignment3 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment3.Name = "alignment3";
		// Container child alignment3.Gtk.Container+ContainerChild
		this.SettingVBox = new global::Gtk.VBox ();
		this.SettingVBox.Name = "SettingVBox";
		this.SettingVBox.Spacing = 6;
		// Container child SettingVBox.Gtk.Box+BoxChild
		this.ToggleCode = new global::Gtk.ToggleButton ();
		this.ToggleCode.CanFocus = true;
		this.ToggleCode.Name = "ToggleCode";
		this.ToggleCode.UseUnderline = true;
		this.ToggleCode.Xalign = 0F;
		this.ToggleCode.Label = global::Mono.Unix.Catalog.GetString ("导出设置");
		this.SettingVBox.Add (this.ToggleCode);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.SettingVBox [this.ToggleCode]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child SettingVBox.Gtk.Box+BoxChild
		this.CodeBox = new global::Gtk.VBox ();
		this.CodeBox.Name = "CodeBox";
		this.CodeBox.Spacing = 6;
		this.SettingVBox.Add (this.CodeBox);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.SettingVBox [this.CodeBox]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Padding = ((uint)(2));
		// Container child SettingVBox.Gtk.Box+BoxChild
		this.ToggleLanguage = new global::Gtk.ToggleButton ();
		this.ToggleLanguage.CanFocus = true;
		this.ToggleLanguage.Name = "ToggleLanguage";
		this.ToggleLanguage.UseUnderline = true;
		this.ToggleLanguage.Xalign = 0F;
		this.ToggleLanguage.Label = global::Mono.Unix.Catalog.GetString ("多国语言设置");
		this.SettingVBox.Add (this.ToggleLanguage);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.SettingVBox [this.ToggleLanguage]));
		w7.Position = 2;
		w7.Expand = false;
		w7.Fill = false;
		// Container child SettingVBox.Gtk.Box+BoxChild
		this.LanguageBox = new global::Gtk.VBox ();
		this.LanguageBox.Name = "LanguageBox";
		this.LanguageBox.Spacing = 6;
		// Container child LanguageBox.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.label8 = new global::Gtk.Label ();
		this.label8.WidthRequest = 120;
		this.label8.Name = "label8";
		this.label8.Xalign = 0.15F;
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("多国语言列表");
		this.hbox1.Add (this.label8);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label8]));
		w8.Position = 0;
		w8.Expand = false;
		w8.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.TextBoxAllLanguages = new global::Gtk.Entry ();
		this.TextBoxAllLanguages.CanFocus = true;
		this.TextBoxAllLanguages.Name = "TextBoxAllLanguages";
		this.TextBoxAllLanguages.IsEditable = true;
		this.TextBoxAllLanguages.InvisibleChar = '●';
		this.hbox1.Add (this.TextBoxAllLanguages);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.TextBoxAllLanguages]));
		w9.Position = 1;
		this.vbox4.Add (this.hbox1);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox1]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox10 = new global::Gtk.HBox ();
		this.hbox10.Name = "hbox10";
		this.hbox10.Spacing = 6;
		// Container child hbox10.Gtk.Box+BoxChild
		this.label9 = new global::Gtk.Label ();
		this.label9.WidthRequest = 120;
		this.label9.Name = "label9";
		this.label9.Xalign = 0.15F;
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("翻译表生成目录");
		this.hbox10.Add (this.label9);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.label9]));
		w11.Position = 0;
		w11.Expand = false;
		w11.Fill = false;
		// Container child hbox10.Gtk.Box+BoxChild
		this.TextBoxTranslation = new global::Gtk.Entry ();
		this.TextBoxTranslation.CanFocus = true;
		this.TextBoxTranslation.Name = "TextBoxTranslation";
		this.TextBoxTranslation.IsEditable = true;
		this.TextBoxTranslation.InvisibleChar = '●';
		this.hbox10.Add (this.TextBoxTranslation);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.TextBoxTranslation]));
		w12.Position = 1;
		this.vbox4.Add (this.hbox10);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox10]));
		w13.Position = 1;
		w13.Expand = false;
		w13.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox11 = new global::Gtk.HBox ();
		this.hbox11.Name = "hbox11";
		this.hbox11.Spacing = 6;
		// Container child hbox11.Gtk.Box+BoxChild
		this.label10 = new global::Gtk.Label ();
		this.label10.WidthRequest = 120;
		this.label10.Name = "label10";
		this.label10.Xalign = 0.15F;
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Language表生成目录");
		this.hbox11.Add (this.label10);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.label10]));
		w14.Position = 0;
		w14.Expand = false;
		w14.Fill = false;
		// Container child hbox11.Gtk.Box+BoxChild
		this.TextBoxLanguage = new global::Gtk.Entry ();
		this.TextBoxLanguage.CanFocus = true;
		this.TextBoxLanguage.Name = "TextBoxLanguage";
		this.TextBoxLanguage.IsEditable = true;
		this.TextBoxLanguage.InvisibleChar = '●';
		this.hbox11.Add (this.TextBoxLanguage);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.TextBoxLanguage]));
		w15.Position = 1;
		this.vbox4.Add (this.hbox11);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox11]));
		w16.Position = 2;
		w16.Expand = false;
		w16.Fill = false;
		this.LanguageBox.Add (this.vbox4);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.LanguageBox [this.vbox4]));
		w17.Position = 0;
		w17.Expand = false;
		w17.Fill = false;
		this.SettingVBox.Add (this.LanguageBox);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.SettingVBox [this.LanguageBox]));
		w18.Position = 3;
		w18.Expand = false;
		// Container child SettingVBox.Gtk.Box+BoxChild
		this.ToggleSpawn = new global::Gtk.ToggleButton ();
		this.ToggleSpawn.CanFocus = true;
		this.ToggleSpawn.Name = "ToggleSpawn";
		this.ToggleSpawn.UseUnderline = true;
		this.ToggleSpawn.Xalign = 0F;
		this.ToggleSpawn.Label = global::Mono.Unix.Catalog.GetString ("其他设置");
		this.SettingVBox.Add (this.ToggleSpawn);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.SettingVBox [this.ToggleSpawn]));
		w19.Position = 4;
		w19.Expand = false;
		w19.Fill = false;
		// Container child SettingVBox.Gtk.Box+BoxChild
		this.SpawnBox = new global::Gtk.VBox ();
		this.SpawnBox.Name = "SpawnBox";
		this.SpawnBox.Spacing = 6;
		// Container child SpawnBox.Gtk.Box+BoxChild
		this.vbox6 = new global::Gtk.VBox ();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox12 = new global::Gtk.HBox ();
		this.hbox12.Name = "hbox12";
		this.hbox12.Spacing = 6;
		// Container child hbox12.Gtk.Box+BoxChild
		this.label11 = new global::Gtk.Label ();
		this.label11.WidthRequest = 120;
		this.label11.Name = "label11";
		this.label11.Xalign = 0.15F;
		this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("关键字列表");
		this.hbox12.Add (this.label11);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.label11]));
		w20.Position = 0;
		w20.Expand = false;
		w20.Fill = false;
		// Container child hbox12.Gtk.Box+BoxChild
		this.textSpawns = new global::Gtk.Entry ();
		this.textSpawns.CanFocus = true;
		this.textSpawns.Name = "textSpawns";
		this.textSpawns.IsEditable = true;
		this.textSpawns.InvisibleChar = '●';
		this.hbox12.Add (this.textSpawns);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.textSpawns]));
		w21.Position = 1;
		this.vbox6.Add (this.hbox12);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox12]));
		w22.Position = 0;
		w22.Expand = false;
		w22.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox13 = new global::Gtk.HBox ();
		this.hbox13.Name = "hbox13";
		this.hbox13.Spacing = 6;
		// Container child hbox13.Gtk.Box+BoxChild
		this.label12 = new global::Gtk.Label ();
		this.label12.WidthRequest = 120;
		this.label12.Name = "label12";
		this.label12.Xalign = 0.15F;
		this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("数据库生成目录");
		this.hbox13.Add (this.label12);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.label12]));
		w23.Position = 0;
		w23.Expand = false;
		w23.Fill = false;
		// Container child hbox13.Gtk.Box+BoxChild
		this.textDatabase = new global::Gtk.Entry ();
		this.textDatabase.CanFocus = true;
		this.textDatabase.Name = "textDatabase";
		this.textDatabase.IsEditable = true;
		this.textDatabase.InvisibleChar = '●';
		this.hbox13.Add (this.textDatabase);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.textDatabase]));
		w24.Position = 1;
		this.vbox6.Add (this.hbox13);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox13]));
		w25.Position = 1;
		w25.Expand = false;
		w25.Fill = false;
		this.SpawnBox.Add (this.vbox6);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.SpawnBox [this.vbox6]));
		w26.Position = 0;
		this.SettingVBox.Add (this.SpawnBox);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.SettingVBox [this.SpawnBox]));
		w27.Position = 5;
		w27.Expand = false;
		this.alignment3.Add (this.SettingVBox);
		w4.Add (this.alignment3);
		this.scrolledwindow1.Add (w4);
		this.MainHBox.Add (this.scrolledwindow1);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.MainHBox [this.scrolledwindow1]));
		w31.Position = 0;
		// Container child MainHBox.Gtk.Box+BoxChild
		this.vbox14 = new global::Gtk.VBox ();
		this.vbox14.Name = "vbox14";
		this.vbox14.Spacing = 6;
		// Container child vbox14.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("PackageName");
		this.hbox2.Add (this.label1);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label1]));
		w32.Position = 0;
		w32.Expand = false;
		w32.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.packageText = new global::Gtk.Entry ();
		this.packageText.CanFocus = true;
		this.packageText.Name = "packageText";
		this.packageText.Text = global::Mono.Unix.Catalog.GetString ("PackageName");
		this.packageText.IsEditable = true;
		this.packageText.InvisibleChar = '●';
		this.hbox2.Add (this.packageText);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.packageText]));
		w33.Position = 1;
		// Container child hbox2.Gtk.Box+BoxChild
		this.buttonRefreshLanguage = new global::Gtk.Button ();
		this.buttonRefreshLanguage.CanFocus = true;
		this.buttonRefreshLanguage.Name = "buttonRefreshLanguage";
		this.buttonRefreshLanguage.UseUnderline = true;
		this.buttonRefreshLanguage.Label = global::Mono.Unix.Catalog.GetString ("刷新多国语言表");
		this.hbox2.Add (this.buttonRefreshLanguage);
		global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.buttonRefreshLanguage]));
		w34.Position = 2;
		this.vbox14.Add (this.hbox2);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox14 [this.hbox2]));
		w35.Position = 0;
		w35.Expand = false;
		w35.Fill = false;
		// Container child vbox14.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.getManager = new global::Gtk.CheckButton ();
		this.getManager.CanFocus = true;
		this.getManager.Name = "getManager";
		this.getManager.Label = global::Mono.Unix.Catalog.GetString ("生成Manager");
		this.getManager.DrawIndicator = true;
		this.getManager.UseUnderline = true;
		this.hbox3.Add (this.getManager);
		global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.getManager]));
		w36.Position = 0;
		// Container child hbox3.Gtk.Box+BoxChild
		this.Language = new global::Gtk.CheckButton ();
		this.Language.CanFocus = true;
		this.Language.Name = "Language";
		this.Language.Label = global::Mono.Unix.Catalog.GetString ("生成多国语言");
		this.Language.DrawIndicator = true;
		this.Language.UseUnderline = true;
		this.hbox3.Add (this.Language);
		global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.Language]));
		w37.Position = 1;
		// Container child hbox3.Gtk.Box+BoxChild
		this.refreshNote = new global::Gtk.CheckButton ();
		this.refreshNote.CanFocus = true;
		this.refreshNote.Name = "refreshNote";
		this.refreshNote.Label = global::Mono.Unix.Catalog.GetString ("刷新表注释(必须关闭Excel)");
		this.refreshNote.DrawIndicator = true;
		this.refreshNote.UseUnderline = true;
		this.hbox3.Add (this.refreshNote);
		global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.refreshNote]));
		w38.Position = 2;
		this.vbox14.Add (this.hbox3);
		global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox14 [this.hbox3]));
		w39.Position = 1;
		w39.Expand = false;
		w39.Fill = false;
		// Container child vbox14.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("选择配置路径");
		this.hbox4.Add (this.label2);
		global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label2]));
		w40.Position = 0;
		w40.Expand = false;
		w40.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.textTableConfig = new global::Gtk.Entry ();
		this.textTableConfig.CanFocus = true;
		this.textTableConfig.Name = "textTableConfig";
		this.textTableConfig.IsEditable = true;
		this.textTableConfig.InvisibleChar = '●';
		this.hbox4.Add (this.textTableConfig);
		global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.textTableConfig]));
		w41.Position = 1;
		this.vbox14.Add (this.hbox4);
		global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.vbox14 [this.hbox4]));
		w42.Position = 2;
		w42.Expand = false;
		w42.Fill = false;
		// Container child vbox14.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("选择要转换的文件夹");
		this.hbox5.Add (this.label3);
		global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label3]));
		w43.Position = 0;
		w43.Expand = false;
		w43.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.textTableFolder = new global::Gtk.Entry ();
		this.textTableFolder.CanFocus = true;
		this.textTableFolder.Name = "textTableFolder";
		this.textTableFolder.IsEditable = true;
		this.textTableFolder.InvisibleChar = '●';
		this.hbox5.Add (this.textTableFolder);
		global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.textTableFolder]));
		w44.Position = 1;
		// Container child hbox5.Gtk.Box+BoxChild
		this.buttonTransformFolder = new global::Gtk.Button ();
		this.buttonTransformFolder.CanFocus = true;
		this.buttonTransformFolder.Name = "buttonTransformFolder";
		this.buttonTransformFolder.UseUnderline = true;
		this.buttonTransformFolder.Label = global::Mono.Unix.Catalog.GetString ("转换");
		this.hbox5.Add (this.buttonTransformFolder);
		global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.buttonTransformFolder]));
		w45.Position = 2;
		this.vbox14.Add (this.hbox5);
		global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.vbox14 [this.hbox5]));
		w46.Position = 3;
		w46.Expand = false;
		w46.Fill = false;
		// Container child vbox14.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox ();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("选择要转换的文件");
		this.hbox6.Add (this.label4);
		global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label4]));
		w47.Position = 0;
		w47.Expand = false;
		w47.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.textTransformFiles = new global::Gtk.Entry ();
		this.textTransformFiles.CanFocus = true;
		this.textTransformFiles.Name = "textTransformFiles";
		this.textTransformFiles.IsEditable = true;
		this.textTransformFiles.InvisibleChar = '●';
		this.hbox6.Add (this.textTransformFiles);
		global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.textTransformFiles]));
		w48.Position = 1;
		// Container child hbox6.Gtk.Box+BoxChild
		this.selectTransformFiles = new global::Gtk.Button ();
		this.selectTransformFiles.CanFocus = true;
		this.selectTransformFiles.Name = "selectTransformFiles";
		this.selectTransformFiles.UseUnderline = true;
		this.selectTransformFiles.Label = global::Mono.Unix.Catalog.GetString ("选择");
		this.hbox6.Add (this.selectTransformFiles);
		global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.selectTransformFiles]));
		w49.Position = 2;
		// Container child hbox6.Gtk.Box+BoxChild
		this.buttonTransform = new global::Gtk.Button ();
		this.buttonTransform.CanFocus = true;
		this.buttonTransform.Name = "buttonTransform";
		this.buttonTransform.UseUnderline = true;
		this.buttonTransform.Label = global::Mono.Unix.Catalog.GetString ("转换");
		this.hbox6.Add (this.buttonTransform);
		global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.buttonTransform]));
		w50.Position = 3;
		this.vbox14.Add (this.hbox6);
		global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.vbox14 [this.hbox6]));
		w51.Position = 4;
		w51.Expand = false;
		w51.Fill = false;
		// Container child vbox14.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox ();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("选择要反转的文件");
		this.hbox7.Add (this.label5);
		global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.label5]));
		w52.Position = 0;
		w52.Expand = false;
		w52.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.textRollbackFiles = new global::Gtk.Entry ();
		this.textRollbackFiles.CanFocus = true;
		this.textRollbackFiles.Name = "textRollbackFiles";
		this.textRollbackFiles.IsEditable = true;
		this.textRollbackFiles.InvisibleChar = '●';
		this.hbox7.Add (this.textRollbackFiles);
		global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.textRollbackFiles]));
		w53.Position = 1;
		// Container child hbox7.Gtk.Box+BoxChild
		this.selectRollbackFiles = new global::Gtk.Button ();
		this.selectRollbackFiles.CanFocus = true;
		this.selectRollbackFiles.Name = "selectRollbackFiles";
		this.selectRollbackFiles.UseUnderline = true;
		this.selectRollbackFiles.Label = global::Mono.Unix.Catalog.GetString ("选择");
		this.hbox7.Add (this.selectRollbackFiles);
		global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.selectRollbackFiles]));
		w54.Position = 2;
		// Container child hbox7.Gtk.Box+BoxChild
		this.buttonRollback = new global::Gtk.Button ();
		this.buttonRollback.CanFocus = true;
		this.buttonRollback.Name = "buttonRollback";
		this.buttonRollback.UseUnderline = true;
		this.buttonRollback.Label = global::Mono.Unix.Catalog.GetString ("转换");
		this.hbox7.Add (this.buttonRollback);
		global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.buttonRollback]));
		w55.Position = 3;
		this.vbox14.Add (this.hbox7);
		global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.vbox14 [this.hbox7]));
		w56.Position = 5;
		w56.Expand = false;
		w56.Fill = false;
		// Container child vbox14.Gtk.Box+BoxChild
		this.hbox8 = new global::Gtk.HBox ();
		this.hbox8.Name = "hbox8";
		this.hbox8.Spacing = 6;
		// Container child hbox8.Gtk.Box+BoxChild
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("选择协议路径");
		this.hbox8.Add (this.label6);
		global::Gtk.Box.BoxChild w57 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.label6]));
		w57.Position = 0;
		w57.Expand = false;
		w57.Fill = false;
		// Container child hbox8.Gtk.Box+BoxChild
		this.textMessage = new global::Gtk.Entry ();
		this.textMessage.CanFocus = true;
		this.textMessage.Name = "textMessage";
		this.textMessage.IsEditable = true;
		this.textMessage.InvisibleChar = '●';
		this.hbox8.Add (this.textMessage);
		global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.textMessage]));
		w58.Position = 1;
		// Container child hbox8.Gtk.Box+BoxChild
		this.buttonMessage = new global::Gtk.Button ();
		this.buttonMessage.CanFocus = true;
		this.buttonMessage.Name = "buttonMessage";
		this.buttonMessage.UseUnderline = true;
		this.buttonMessage.Label = global::Mono.Unix.Catalog.GetString ("转换");
		this.hbox8.Add (this.buttonMessage);
		global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.buttonMessage]));
		w59.Position = 2;
		this.vbox14.Add (this.hbox8);
		global::Gtk.Box.BoxChild w60 = ((global::Gtk.Box.BoxChild)(this.vbox14 [this.hbox8]));
		w60.Position = 6;
		w60.Expand = false;
		w60.Fill = false;
		// Container child vbox14.Gtk.Box+BoxChild
		this.hbox9 = new global::Gtk.HBox ();
		this.hbox9.Name = "hbox9";
		this.hbox9.Spacing = 6;
		// Container child hbox9.Gtk.Box+BoxChild
		this.label7 = new global::Gtk.Label ();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("选择数据库配置路径");
		this.hbox9.Add (this.label7);
		global::Gtk.Box.BoxChild w61 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.label7]));
		w61.Position = 0;
		w61.Expand = false;
		w61.Fill = false;
		// Container child hbox9.Gtk.Box+BoxChild
		this.textDatabaseConfig = new global::Gtk.Entry ();
		this.textDatabaseConfig.CanFocus = true;
		this.textDatabaseConfig.Name = "textDatabaseConfig";
		this.textDatabaseConfig.IsEditable = true;
		this.textDatabaseConfig.InvisibleChar = '●';
		this.hbox9.Add (this.textDatabaseConfig);
		global::Gtk.Box.BoxChild w62 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.textDatabaseConfig]));
		w62.Position = 1;
		// Container child hbox9.Gtk.Box+BoxChild
		this.buttonDatabase = new global::Gtk.Button ();
		this.buttonDatabase.CanFocus = true;
		this.buttonDatabase.Name = "buttonDatabase";
		this.buttonDatabase.UseUnderline = true;
		this.buttonDatabase.Label = global::Mono.Unix.Catalog.GetString ("转换");
		this.hbox9.Add (this.buttonDatabase);
		global::Gtk.Box.BoxChild w63 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.buttonDatabase]));
		w63.Position = 2;
		this.vbox14.Add (this.hbox9);
		global::Gtk.Box.BoxChild w64 = ((global::Gtk.Box.BoxChild)(this.vbox14 [this.hbox9]));
		w64.Position = 7;
		w64.Expand = false;
		w64.Fill = false;
		// Container child vbox14.Gtk.Box+BoxChild
		this.progressBar = new global::Gtk.ProgressBar ();
		this.progressBar.Name = "progressBar";
		this.progressBar.Text = "";
		this.vbox14.Add (this.progressBar);
		global::Gtk.Box.BoxChild w65 = ((global::Gtk.Box.BoxChild)(this.vbox14 [this.progressBar]));
		w65.Position = 8;
		w65.Expand = false;
		w65.Fill = false;
		// Container child vbox14.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.TextViewLog = new global::Gtk.TextView ();
		this.TextViewLog.CanFocus = true;
		this.TextViewLog.Name = "TextViewLog";
		this.GtkScrolledWindow1.Add (this.TextViewLog);
		this.vbox14.Add (this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w67 = ((global::Gtk.Box.BoxChild)(this.vbox14 [this.GtkScrolledWindow1]));
		w67.Position = 9;
		this.MainHBox.Add (this.vbox14);
		global::Gtk.Box.BoxChild w68 = ((global::Gtk.Box.BoxChild)(this.MainHBox [this.vbox14]));
		w68.Position = 1;
		w3.Add (this.MainHBox);
		this.GtkScrolledWindow.Add (w3);
		this.MenuVBox.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w71 = ((global::Gtk.Box.BoxChild)(this.MenuVBox [this.GtkScrolledWindow]));
		w71.Position = 1;
		this.Add (this.MenuVBox);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 994;
		this.DefaultHeight = 481;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.TinyPNGAction.Activated += new global::System.EventHandler (this.OnClickTinyPNG);
		this.ToggleCode.Toggled += new global::System.EventHandler (this.OnToggleCode);
		this.ToggleLanguage.Toggled += new global::System.EventHandler (this.OnToggleLanguage);
		this.ToggleSpawn.Toggled += new global::System.EventHandler (this.OnToggleSpawn);
		this.buttonTransformFolder.Clicked += new global::System.EventHandler (this.buttonTransformFolder_Click);
		this.selectTransformFiles.Clicked += new global::System.EventHandler (this.selectTransformFiles_Click);
		this.buttonTransform.Clicked += new global::System.EventHandler (this.buttonTransform_Click);
		this.selectRollbackFiles.Clicked += new global::System.EventHandler (this.selectRollbackFiles_Click);
		this.buttonRollback.Clicked += new global::System.EventHandler (this.buttonRollback_Click);
		this.buttonMessage.Clicked += new global::System.EventHandler (this.buttonMessage_Click);
		this.buttonDatabase.Clicked += new global::System.EventHandler (this.buttonDatabase_Click);
	}
}
